language: node_js
node_js:
- '11'
before_install:
- npm install -g npm@'^5.10.0'
- npm install -g RadonApp/radon-extension-build#$TRAVIS_BRANCH || npm install -g RadonApp/radon-extension-build#develop
install:
- neb travis:install $TRAVIS_BRANCH
- neb package:validate
- git diff --exit-code
script:
- npm run test
- npm run lint
- if [ ! -f ./Build/Coverage/lcov.info ]; then exit 1; fi
after_success:
- npm install -g coveralls
- cat ./Build/Coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: ci@radon.app
  api_key:
    secure: fTnn4GoMFC65j1lTYvjA0FydKdA+4F+wOVmHZKxeopXZtUZIzWTnZxEa7+KrqpTEZTDrfsTe2sxhnPj7SC2lKTPQDEr7bn8MkUbggv0sEfpMIk8aqZAEgsXDqnBou9d72/nfu4laZtLuyNuOY21GanU290ihjp1YpTMlOERKJhn7hV8npgwpsHQogV0w5CtzntK7BC9WVkWKtkskmJ3I/ymPwxb2T7PHkjK4fXn7nUxM2JaZWyvGyY08dLosUakN88WzO1piBKfUHdCWiZ2sFavrteeKCyX+gmo1HFIxqwWrX6gtxTQbAg4j6xPHrRwduF65JiOD+Evg54MfqElKWNA2ICQN44j7trmwQNSPMnNtdcLxRXIRlkcV5C9Dx//d1q19iiuZKSOJxhyNJutwn2tiI4xQsG5my1SIq4G2xzDpiXZeF2NyOhoP/fhXTba9xHDpu++aboXx0vW9/Fwqyji6DFyZs0RhuRXGuEOtTP9ms2ow7KF85lWhssdZ6Npdt9j71c2movz3idx60jJyzfnEJWCetHq8AsWR4uNkEvlh8ZQJWTp9xJMSK3/GzDZ5u4JGMDaUDg76zIYk4hGE+n6XpmFzLIgDnzBqXBRr16d777Q4JFK3BT3ZbduhqoxpOq9IIvDpZeIfdHoZ9Uowv0QV08r5v1FrgNjQSUciqtA=
  on:
    tags: true
    repo: RadonApp/radon-extension-plugin-googlemusic
